version: '3'

services:
  db:
    image: mdillon/postgis:10
    volumes:
    - './data:/var/lib/postgresql/data'
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
    - 5432:5432
  start_dependencies:
    image:  mdillon/postgis:10
    depends_on:
    - db
    command: >
      /bin/bash -c "sleep 5 && echo 'comecou -------------------------------' && PGPASSWORD=postgres psql -h db  -U postgres -tc \"SELECT 1 FROM pg_database WHERE datname = 'trantor'\" | grep -q 1 || PGPASSWORD=postgres psql -h db -U postgres -c \"CREATE DATABASE forum\""
